class Setting(object):
    pass

MISC = Setting()

IS_CATEGORICAL = Setting()
IS_CATEGORICAL.THRESHOLD = 0.1

GAP_STATISTIC = Setting()
GAP_STATISTIC.RANDOMIZED_PCA_THRESHOLD = 10
GAP_STATISTIC.NUM_CLUSTERS_WITHOUT_IMPROVEMENT = 5
GAP_STATISTIC.MAXIMUM_DECLINE = 0.5

QUICK_CACHE = Setting()
QUICK_CACHE.DIRECTORY = "quick_cache"
